# Generated by Django 2.1.5 on 2021-10-02 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.catagory'),
        ),
    ]
